version: 2.1
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: CI=true npm run build
   test:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: npm run test
   hithere:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: echo "Hellloooooooooo!"
   jacotest:
      docker:
       - image: circleci/node:latest
      steps:
       - checkout
       - run: echo "Jaco is running tests on circleCI!"
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - hithere
      - jacotest
      - test:
          requires:
            - hithere
            - jacotest
            